Trying to merge the 2 steps into 1 action

diff --git a/.github/workflows/LinkExtract.yml b/.github/workflows/LinkExtract.yml
--- a/.github/workflows/LinkExtract.yml
+++ b/.github/workflows/LinkExtract.yml
@@ -36,16 +36,17 @@ jobs:
           git commit -m "Update Outputs"
           git push origin HEAD
 
+      - name: Download Links with wget
+        run: |
+          wget --quiet --continue -i .github/outputs/Action-link.txt -P downloads/ 2>&1 | tee -a wget_errors.log
+          if [ -s wget_errors.log ]; then
+            echo "Wget errors detected. Failing the build."
+            exit 1
+          fi
+
       - name: Store Logs as Artifacts
-        if: steps.check-changes.outputs.check-changes == 'Changes found'
+        if: steps.check-changes.outputs.check-changes == 'Changes found' || steps.Download Links with wget.outcome == 'failure'
         uses: actions/upload-artifact@v2
         with:
           name: logs
-          path: changes.log
-
-      - name: Download Links with wget
-        run: |
-          wget --quiet --continue -i .github/outputs/Action-link.txt -P downloads/ || {
-            echo "Wget errors detected. Failing the build."
-            exit 1
-          }
+          path: changes.log, wget_errors.log
