Update LinkExtract.yml

diff --git a/.github/workflows/LinkExtract.yml b/.github/workflows/LinkExtract.yml
--- a/.github/workflows/LinkExtract.yml
+++ b/.github/workflows/LinkExtract.yml
@@ -18,24 +18,24 @@ jobs:
           | grep -Evi 'reddit\.com|apkmirror\.com|docs\.google\.com|1drv\.ms|m3\.material\.io|en\.wikipedia\.org|pling\.com|github\.com/TeaOwO/Material-You-Apps/assets|m3-markdown-badges\.vercel\.app|android\.stackexchange\.com|coolapk\.com|github\.com/TeaEndsAcronyms/Material-You-Apps/assets|apkmonk\.com' \
           | sed 's/[()]//g' \
           | sed 's/[<>]//g' \
-          | sed 's/[#\d+\]//g'
-          | sed 's/ 🍴Fork/`\0`/g' > .github/outputs/Action-link.txt
+          | sed 's/[0-9#]//g' \
+          | sed 's/ 🍴Fork/`\\0`/g' > .github/outputs/Action-link.txt
 
-    - name: Download Links with wget
-      run: |
-       max_retries=2
-        while IFS= read -r link; do
-         retries=0
-        while [ $retries -lt $max_retries ]; do
-        wget --quiet --continue "$link" -P downloads/ || {
-          echo "Failed to download: $link" >> wget_errors.log
-          retries=$((retries + 1))
-        }
-        if [ $? -eq 0 ]; then
-          break
-        fi
-        done
-       done < .github/outputs/Action-link.txt
+      - name: Download Links with wget
+        run: |
+          max_retries=2
+          while IFS= read -r link; do
+            retries=0
+            while [ $retries -lt $max_retries ]; do
+              wget --quiet --continue "$link" -P downloads/ || {
+                echo "Failed to download: $link" >> wget_errors.log
+                retries=$((retries + 1))
+              }
+              if [ $? -eq 0 ]; then
+                break
+              fi
+            done
+          done < .github/outputs/Action-link.txt
 
       - name: Commit Changes
         run: |
